/*next update change the name of the table to Early_Warning_DimTerms to follow dim/fact conventions*/

DROP TABLE CUSTOM.CUSTOM_EARLY_WARNING_TERMS

CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_TERMS (
TERMKEY INT PRIMARY KEY,
TERMID INT,
TERMNAME VARCHAR(40),
YEARID INT,
ABBREVIATION VARCHAR(10),
COMMONTERM INT,
SCHOOLID INT,
FIRSTDAY DATE,
LASTDAY DATE,
SCHOOLYEAR4DIGIT INT,
SEASON VARCHAR(10));

CREATE INDEX EW_TERMS ON CUSTOM.CUSTOM_EARLY_WARNING_TERMS (TERMKEY);

INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_TERMS --(TERMKEY,TERMID,TERMNAME,YEARID,ABBREVIATION,COMMONTERM,SCHOOLID,FIRSTDAY,LASTDAY,SCHOOLYEAR4DIGIT,SEASON)
SELECT
SUB.TERMKEY,
SUB.TERMID,
SUB.TERMNAME,
SUB.YEARID,
SUB.ABBREVIATION,
CASE
	WHEN TERMTYPE = 'Trimester' AND TERMNUMBER = 3 THEN 4
	WHEN TERMTYPE = 'Semester' AND TERMNUMBER = 1 THEN 2
	WHEN TERMTYPE = 'Semester' AND TERMNUMBER = 2 THEN 4
	ELSE TERMNUMBER
END COMMONTERM,
SUB.SCHOOLID,
SUB.FIRSTDAY,
SUB.LASTDAY,
CASE -- create a 4 digit year (YYYY) field -- added 7/13
	WHEN DATEPART(MM,SUB.LASTDAY) BETWEEN 7 AND 12 THEN DATEPART(YYYY,SUB.LASTDAY)+1
	ELSE DATEPART(YYYY,SUB.LASTDAY) 
END SCHOOLYEAR4DIGIT,
CASE
	WHEN  TERMNUMBER = 0 THEN 'Summer'
	WHEN  TERMNUMBER = 1 AND TERMTYPE != 'Semester' THEN 'Fall'
	WHEN (TERMNUMBER = 2 AND TERMTYPE != 'Semester') OR (TERMTYPE = 'Semester' AND TERMNUMBER = 1) THEN 'Winter'
	WHEN (TERMNUMBER = 4 AND TERMTYPE = 'Quarter') OR (TERMNUMBER = 3 AND TERMTYPE = 'Trimester') OR (TERMNUMBER = 2 AND TERMTYPE = 'Semester') THEN 'Spring'
	ELSE '-----'
END AS SEASON
FROM(
	SELECT
	CAST(CAST(ID AS VARCHAR) + CAST(SCHOOLID AS VARCHAR) AS INT) AS TERMKEY,
	ID AS TERMID,
	NAME AS TERMNAME,
	YEARID AS YEARID,
	ABBREVIATION AS ABBREVIATION,
	SCHOOLID AS SCHOOLID,
	FIRSTDAY AS FIRSTDAY,
	LASTDAY AS LASTDAY,
	CASE 
	  WHEN NAME LIKE 'Advisory%' OR NAME LIKE 'Quarter%' THEN 'Quarter'
	  WHEN NAME LIKE 'Trimester%' THEN 'Trimester'
	  WHEN NAME LIKE 'Semester%' AND NAME NOT LIKE '%Final%' THEN 'Semester'
	  WHEN NAME LIKE '2%-2%' THEN 'Full Year'
	  WHEN NAME LIKE 'School Year' THEN 'Academic Year'
	  WHEN NAME LIKE 'Summer%' THEN 'Summer'
	  ELSE '-----' END AS TERMTYPE,
	CASE
	  WHEN NAME LIKE 'Summer%' THEN 0
	  WHEN NAME LIKE '%-%' THEN 6 
	  WHEN NAME LIKE 'School Year' THEN 5 
	  WHEN NAME LIKE '%Final%' THEN -1
	  WHEN CAST(RIGHT(ABBREVIATION,1) AS INT) BETWEEN 1 AND 4 THEN CAST(RIGHT(ABBREVIATION,1) AS INT)
	  ELSE '-----'
	END AS TERMNUMBER
	FROM POWERSCHOOL.POWERSCHOOL_TERMS
	WHERE SCHOOLID NOT IN (0,999999,2001) AND YEARID>=20 --EXCLUDE GRAD SCHOOL, ALUMNI, AND NPP; EXCLUDE SCHOOL YEARS BEFORE 2010
	) SUB
;

/*add a row of termkey -1 so you don't drop records on with an inner join*/
INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_TERMS
VALUES(-1,-1,'-----',-1,'-----',-1,-1,'01-01-1900','01-01-1900',-1,'-----');
