DROP VIEW CUSTOM.CUSTOM_TERM_CONVERSIONS;

CREATE VIEW custom.custom_term_conversions AS

SELECT DISTINCT --CONVERT GRADEPERIOD TO STORECODE TO UPP 
T.ID, --NEED THIS
T.NAME, --NEED THIS
T.SCHOOLID, --JOIN
PG_TERMS.FINALGRADENAME, --JOIN
T.ABBREVIATION,
T.YEARID --JOIN 
FROM POWERSCHOOL.POWERSCHOOL_TERMS T
LEFT JOIN(
	SELECT DISTINCT
	STARTDATE,
	ENDDATE,
	CC.SCHOOLID,
	FINALGRADENAME
	FROM POWERSCHOOL.POWERSCHOOL_PGFINALGRADES PG
	--LEFT JOIN POWERSCHOOL.POWERSCHOOL_STUDENTS CC ON CC.ID = P.STUDENTID
	JOIN POWERSCHOOL.POWERSCHOOL_CC CC ON CC.STUDENTID = PG.STUDENTID AND CC.SECTIONID = PG.SECTIONID
) PG_TERMS ON PG_TERMS.SCHOOLID = T.SCHOOLID AND ((PG_TERMS.STARTDATE = T.FIRSTDAY AND PG_TERMS.ENDDATE = T.LASTDAY) OR PG_TERMS.FINALGRADENAME = T.ABBREVIATION)
WHERE T.SCHOOLID>0
--AND T.SCHOOLID = 2000
--AND T.YEARID = 26
--ORDER BY T.SCHOOLID, T.ID
and PG_TERMS.FINALGRADENAME is not null
;
